# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'




## => Site Settings
##############################
text_color_theme: default # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
url: https://xftony.github.io/ 
baseurl: /xftony.github.io
title: xftony's blog
description: > # this means to ignore newlines until "Language & timezone"
  xftony's Blog


## => Language and Timezone
##############################
lang: # the language of your site, "en" (default, English), "zh"(简体中文), "zh-Hans"(简体中文), "zh-Hant"(繁體中文)
timezone: Asia/Shanghai # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values


## => Author and Social
##############################
author:
  name: Tony SHI
  email: srl11@foxmail.com 
  facebook: # your Facebook username
  twitter: # your Twitter username
  github: xftony 
  linkedin: # your Linkedin username
  googleplus: # your Google+ username
  weibo: # your Weibo username
  douban: # your Douban username


## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: xftony.github.io
repository_tree: master


## => Navigation
##############################
paths:
  base: /
  home: /
  all:  /all.html
  rss:  /feed.xml

nav_lists:
  - titles:
      en: About
      zh: 关于
      zh-Hans: 关于
      zh-Hant: 關於
    url: /about.html


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->
excerpt_type: html # text (default), html

## TOC
toc:
  selectors: # "h1,h2,h3" (default)

## Markdown Enhancements

# Mathjax
mathjax: # false (default), true
mathjax_autoNumber: # false (default), true

# Mermaid
mermaid: # false (default), true

# Chart
chart: # false (default), true


## => Paginate
##############################
paginate: 8
paginate_path: /blog/page:num # don't change this unless for special need


## => Sources
##############################
sources: # bootcdn (default), unpkg


## => Comments
##############################
## Disqus
disqus:
  shortname: # the Disqus shortname for the site

## Gitalk
# please refer to https://github.com/gitalk/gitalk for more info.
gitalk:
  clientID: ed5fadc7a9299dfcd0cd
  clientSecret: 8973e2bbe81193cc8d9c3b119e01762cb41e0561
  repository: xftony.github.io
  owner: xftony
  admin: # Github repo owner and collaborators, only these guys can initialize github issues, IT IS A LIST.
    - xftony



## => Pageview
##############################
## Leancloud
leancloud:
  app_id: cFPzImRVjxj3Wh6BPQ4BSy1H-gzGzoHsz
  app_key: M4tH0spHVyi4PdhoGt6IQn0o
  app_class: Counter


## => Analytics
##############################
## Google Analytics
ga_tracking_id: # Google Analytics id for the site

baidu-analysis: ff9943f368cb96a631f6ca5425a9f59f

## => Build
##############################
markdown: kramdown
highlighter: rouge
permalink: date

exclude:
  - CHANGELOG.md
  - CHECKLIST.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor


## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji